owner: vulcain65
repo: upptime

sites:
  - name: e-berga
    url: https://e-berga.info
  - name: motards-en-voyage
    url: https://motards-en-voyage.com//robots.txt
  - name: b.emdayo
    url: https://b.emdayo.fr/
  - name: o.emdayo
    url: https://o.emdayo.fr/

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Vulcain
  theme: night
  introTitle: ""
  introMessage: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: ""
